import Head from 'next/head'
import Image from 'next/image'
import AnimationsCupe from '../components/home/animationsCupe'
import Layout from '../components/layout'
import { Icon } from '@iconify/react'
import Link from 'next/link'
import HomeContext from '../components/home/homeContext'
import axios from 'axios'
import { useSession } from 'next-auth/react'
import { useSelector, useDispatch } from 'react-redux'
import { SET_POSTS } from 'store/postsSlices'

import { wrapper } from 'store'
import { SET_CATEGORIES } from 'store/categoriesSlices'

export default function Home({ postsData, categoriesData }: any) {
  const { data: session } = useSession()
  return (
    <div className='App'>
      <Head>
        <title>SoftDevTerms - Musa Yazlık</title>
        <meta name='description' content='Generated by SoftDevWords' />
        <meta name='author' content='Musa Yazlık' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <main className=''>
          <div className='flex  min-h-[700px] pt-52 pb-24 relative '>
            <AnimationsCupe />
            <section className='container mx-auto max-w-3xl flex flex-col justify-center items-start rounded-3xl  '>
              <div className='flex flex-col items-center  '>
                <h1 className=' text-2xl lg:text-5xl font-bold text-zinc-200 shadow-lg shadow-blue-800/20 bg-[conic-gradient(at_bottom,_var(--tw-gradient-stops))] from-blue-700/20 via-blue-900/20 to-zinc-900/20 backdrop-blur-sm px-14 py-6 mb-12 border-b-4 border-blue-800'>
                  SoftDeTerms
                </h1>
                <p className=' bg-zinc-800/20 dark:bg-zinc-900/20 text-zinc-200 text-center px-4 sm:px-14 py-8 backdrop-blur-sm font-medium text-md sm:text-lg leading-7 '>
                  As a software developer, learn words and terms related to the
                  software profession from a single point.
                </p>
              </div>

              <div className='col-span-12 lg:col-span-4 flex w-full items-center justify-center h-full mt-16 gap-x-4 md:gap-x-8  text-zinc-200'>
                <Link href={'/'} className='hover:scale-150 duration-300 '>
                  <Icon
                    icon='ph:facebook-logo-duotone'
                    width={32}
                    height={32}
                    className='hover:drop-shadow-md'
                  />
                </Link>
                <Link href={'/'} className='hover:scale-150 duration-300 '>
                  <Icon
                    icon='ph:twitter-logo-duotone'
                    width={32}
                    height={32}
                    className='hover:drop-shadow-md'
                  />
                </Link>
                <Link
                  href={'/'}
                  className='hover:scale-150 duration-300 rounded-3xl'>
                  <Icon
                    icon='ph:instagram-logo-duotone'
                    width={32}
                    height={32}
                    className='hover:drop-shadow-md'
                  />
                </Link>
                <Link
                  href={'/'}
                  className='hover:scale-150 duration-300 rounded-3xl'>
                  <Icon
                    icon='ph:linkedin-logo-duotone'
                    width={32}
                    height={32}
                    className='hover:drop-shadow-md'
                  />
                </Link>
                <Link
                  href={'/'}
                  className='hover:scale-150 duration-300 rounded-3xl'>
                  <Icon
                    icon='ph:github-logo-duotone'
                    width={32}
                    height={32}
                    className='hover:drop-shadow-md'
                  />
                </Link>
                <Link
                  href={'/'}
                  className='hover:scale-150 duration-300 rounded-3xl'>
                  <Icon
                    icon='ph:dribbble-logo-duotone'
                    width={32}
                    height={32}
                    className='hover:drop-shadow-md'
                  />
                </Link>
              </div>
            </section>
          </div>
          <div className='container mx-auto mt-14'>
            <div className='flex items-center justify-end mr-8 '>
              {session && (
                <Link
                  href={'/post/create'}
                  className='flex gap-2 items-center px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white dark:text-blue-900 font-semibold text-xl rounded-md border-2 border-b-4 border-blue-800 hover:scale-105 duration-300 shadow-md shadow-blue-600/40 dark:shadow-blue-800/40 mb-4'>
                  <Icon icon='ic:twotone-add-circle' fontSize={28} />
                  Post Create
                </Link>
              )}
            </div>
          </div>
          <HomeContext />
        </main>
      </Layout>
    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async () => {
    const postsRes = await fetch(`${process.env.NEXT_PUBLIC_URL}/api/posts`)
    const categoriesRes = await fetch(
      `${process.env.NEXT_PUBLIC_URL}/api/categories`
    )
    const categoriesData = await categoriesRes.json()
    const postsData = await postsRes.json()
    await store.dispatch(SET_CATEGORIES(categoriesData.data) as any)
    await store.dispatch(SET_POSTS(postsData.posts) as any)
    return {
      props: { postsData, categoriesData },
    }
  }
)
